// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL5hww-FDv-_YGaS5g7-TuHPBA-emHpcg',
    appId: '1:102944635603:web:d1f50a209e6d3b4981f226',
    messagingSenderId: '102944635603',
    projectId: 'database-7ae27',
    authDomain: 'database-7ae27.firebaseapp.com',
    storageBucket: 'database-7ae27.appspot.com',
    measurementId: 'G-G7KZK93503',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPag_rwfZHwrkEiIN8BU5rZKnJLqxRa08',
    appId: '1:102944635603:android:dfbcb18f167cbe2881f226',
    messagingSenderId: '102944635603',
    projectId: 'database-7ae27',
    storageBucket: 'database-7ae27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_cBGU7bI9Sk63_e02_05p_7l57LNvJGQ',
    appId: '1:102944635603:ios:fc79a7c265fb3fd181f226',
    messagingSenderId: '102944635603',
    projectId: 'database-7ae27',
    storageBucket: 'database-7ae27.appspot.com',
    iosBundleId: 'com.example.lostfound',
  );
}
